### PR TITLE
feat: bump workload version to 2.0.4

### PR DESCRIPTION
**Pull request by ca-scribner**
Merge after #16, #18

### CODE REVIEW

**Comment by ca-scribner** [comment]
tests weren't working at all for me locally when I set this up.  I'll revisit tomorrow

**Comment by ca-scribner** [comment]
should be g2g now (after 16 and 18 are merged)

**Review by DnPlas — COMMENTED** [review]
I am still confused about the `sample/metacontroller:tag` in metadata.yaml, if that's how it works I am fine.

**Comment by DnPlas** [comment]
LGTM, you can merge after rebasing and the CI passes.

**Review by DnPlas — APPROVED** [review]

**Pull request merged**
